pluginManagement {
    repositories {
        maven { url 'https://maven.fabricmc.net/' }
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = 'FabricMods'

include ':resourcelib:API', ':resourcelib:Mod'

include ':events', ':commands', ':beacontweaks', ':essence', ':mcrpg',
    ':fakeplayer', ':telekinesis', ':spawnertweaks', ':wrench', ":quieter"